TI demo version

diff --git a/utils/net-scripts/v2/create-gre-tunnel b/utils/net-scripts/v2/create-gre-tunnel
--- a/utils/net-scripts/v2/create-gre-tunnel
+++ b/utils/net-scripts/v2/create-gre-tunnel
@@ -1,23 +1,23 @@
 #! /bin/bash
 #COUNT
 
-#SERVER
-
 if [ "$#" -ne 1 ]; then
     echo "start-stocat COUNT"
     exit 1
 fi
 
-COUNT=$(($1*2))
+if [ "$1" -eq 1 ]; then
+    echo "COUNT cannot be 1"
+    exit 1
+fi
 
-LOCALIP="10.0.0.$COUNT"
+COUNT=$1
+LOCALIP="10.0.0.1"
 
-REMOTEIP="10.0.0.$(($COUNT+1))"
+REMOTEIP="10.0.0.$COUNT"
 
 
-echo $REMOTEIP $LOCALIP 
-
-IFACE="gre-lr$1"
+IFACE="gre-lr$COUNT"
 ip link add $IFACE type gretap remote $REMOTEIP local $LOCALIP
 ip link set $IFACE up
 
